[meta]
name = "Grinding Stats"
author = "Drek"
category = "Overlay"
version = "2.1.8"
siteid = 158

[script]
module = "GrindingStats"
optional_dependencies = [
    "NadeoServices",
    "ChampionMedals",
    "DuckMedals",
    "WarriorMedals",
]
timeout = 5000
exports = ["src/Export/Export.as"]
